"""Add Revendedor and Compra tables

Revision ID: 5ed406ab9826
Revises: 
Create Date: 2022-08-10 12:09:38.244821

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "5ed406ab9826"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "revendedores",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("cpf", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("nome_completo", sa.String(), nullable=True),
        sa.Column("senha_com_hash", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_revendedores_cpf"), "revendedores", ["cpf"], unique=True)
    op.create_index(
        op.f("ix_revendedores_email"), "revendedores", ["email"], unique=True
    )
    op.create_index(op.f("ix_revendedores_id"), "revendedores", ["id"], unique=False)
    op.create_table(
        "compras",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("codigo", sa.String(), nullable=True),
        sa.Column("valor", sa.String(), nullable=True),
        sa.Column("data", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("porcentagem_de_cashback", sa.String(), nullable=True),
        sa.Column("revendedor_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["revendedor_id"],
            ["revendedores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_compras_codigo"), "compras", ["codigo"], unique=True)
    op.create_index(op.f("ix_compras_id"), "compras", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_compras_id"), table_name="compras")
    op.drop_index(op.f("ix_compras_codigo"), table_name="compras")
    op.drop_table("compras")
    op.drop_index(op.f("ix_revendedores_id"), table_name="revendedores")
    op.drop_index(op.f("ix_revendedores_email"), table_name="revendedores")
    op.drop_index(op.f("ix_revendedores_cpf"), table_name="revendedores")
    op.drop_table("revendedores")
    # ### end Alembic commands ###
