"""Create api user table

Revision ID: 96bca8ca3135
Revises: ca3a50cb6034
Create Date: 2022-08-14 16:19:29.097550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96bca8ca3135'
down_revision = 'ca3a50cb6034'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_users_id'), 'api_users', ['id'], unique=False)
    op.create_index(op.f('ix_api_users_username'), 'api_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_users_username'), table_name='api_users')
    op.drop_index(op.f('ix_api_users_id'), table_name='api_users')
    op.drop_table('api_users')
    # ### end Alembic commands ###
