"""Add cash back criterios table

Revision ID: ca3a50cb6034
Revises: ec2d57b33850
Create Date: 2022-08-12 22:00:50.407187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca3a50cb6034'
down_revision = 'ec2d57b33850'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashback_criterios',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('intervalo', postgresql.NUMRANGE(), nullable=False),
    sa.Column('porcentagem_de_cashback', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashback_criterios_id'), 'cashback_criterios', ['id'], unique=False)
    op.drop_column('compras', 'porcentagem_de_cashback')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compras', sa.Column('porcentagem_de_cashback', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_cashback_criterios_id'), table_name='cashback_criterios')
    op.drop_table('cashback_criterios')
    # ### end Alembic commands ###
