"""Add status_compra_default to Revendedor

Revision ID: ec2d57b33850
Revises: 8f05393b636b
Create Date: 2022-08-12 19:49:13.999547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2d57b33850'
down_revision = '8f05393b636b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revendedores', sa.Column('status_compra_default', sa.Enum('em_validacao', 'aprovado', name='statusenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revendedores', 'status_compra_default')
    # ### end Alembic commands ###
